# 📚 11 예외와 에러 처리
### 📖 Error 객체
JS에는 내장된 Error객체가 있고, 인스턴스 생성 단계에서 어떤 문제인지 에러 메세지를 넣어주면 된다. 
```js
function validateEmail(email) {
    return email.match(/@/) ? email : new Error(`invalid email: ${email}`);
}

const email = "jane@doe.com";
const result = validateEmail(email);

if(result instanceof Error) {
    console.log(`Error: ${result.message}`);
}else {
    console.log(`Valid email: ${result}`);
}
```

### 📖 예외처리 구조(try/catch/finally)
예외처리(Exception Handling)는 에러를 컨트롤하는 메커니즘을 말한다. 에외 처리는 예상치 못한 상황에 대처하하는 방법으로 사용자가 개발자의 의도와는 다르게 사용했을 때 발생하는 상황을 처리하기 위함이다.

Error 객체를 통해 에러로써 처리할 수도 있지만, try...catch...finally 구조를 통해 예외로 처리할 수도 있다. 에러와 예외처리의 차이는, 에러는 결함으로 프로그램을 강제 종료하지만 예외 처리는 발생한 에러를 나름의 방법으로 처리하여 프로그램을 멈추지 않고 계속 실행하도록 만들어준다.

```js
const email = null;
try {
    if(email.match(/@/)) {
        throw new Error(`invalid email: ${email}`)
    }
    console.log(`Valid email: ${result}`);
}catch(error) {
    console.log(`Error: ${errror.message}`);
}finally {
    console.log("...always executed");
}
```

예외처리의 구조는 위와 같이 기본적으로 try...catch...finally로 구성된다. 
- try는 코드가 실행되는 영역으로 문제가 발생하면 에러를 일으키는 영역이다.
- try에서 일어난 에러를 잡아서 예외 처리를 할 때에 catch를 구성한다.
- finally은 에러가 일어나든 일어나지 않든 반드시 실행해야하는 코드의 영역으로 특히 자원처리(파일, http연결 etc)를 정리할 때 많이 사용한다.

### 📖 예외발생(throw)
JS가 에러를 일으키기만 기다릴 필요없이 직접 에러를 일으켜서 예외 처리 작업을 진행시킬 수 있다. 그때 사용하는 키워드가 throw이다. JS에선 에러를 일으킬 때 꼭 객체만이 아니라 숫자나 문자열 등 어떤 값이든 catch절에 넘길 수는 있으나 기본적으론 Error 객체를 받을 것을 기대하기 때문에 가급적이면 Error 객체로 처리해주는 것이 좋다. 

### 📖 예외 처리와 호출스택(Call Stack)
JS의 흐름을 보다보면 A함수가 B함수를 호출하고 B함수가 C를 호출하는 등 여러 처리가 호출을 통해서 이루어진다. 이러한 처리를 추적할 필요가 있는데, 추적을 위해 함수를 호출할 때마다 실행 컨텍스트를 만들어 호출 스택에 쌓아서 관리한다.

이와 같이 호출 스택에 쌓아둔 처리들 중 문제를 일으키는 부분(에러)이 있으면, 문제를 일으킨 부분부터 에러를 캐치해줄 때까지 호출 스택을 따라 올라간다. 에러는 호출 스택 어디에서든 캐치할 수 있는데, 만약 캐치해주지 않으면 프로그램은 멈추게 된다.

에러가 발생한 부분을 호출스택을 추적하여 모두 기록해준다는 장점도 있다. C함수에서 에러가 발생하면, C함수는 B함수에서 호출 됐고, B함수는 A함수에서 불렀다는 traceroute를 남겨준다.